// packages/react-component-lib/src/createComponent.tsx
import React from 'react';
import * as ReactDom from 'react-dom';
import { dashToPascalCase } from './utils';
import { attachEventProps } from './attachEventProps';

export function createReactComponent<PropType, ElementType>(
  tagName: string,
  attributeValues: string[] = [],
) {
  const displayName = dashToPascalCase(tagName);

  type IonicReactInternalProps = {
    forwardedRef?: React.RefObject<ElementType>;
    children?: React.ReactNode;
  };
  type InternalProps = PropType & IonicReactInternalProps;

  type IonicReactExternalProps = {
    ref?: React.RefObject<ElementType>;
    children?: React.ReactNode;
  };

  class ReactComponent extends React.Component<InternalProps> {
    constructor(props: PropType & IonicReactInternalProps) {
      super(props);
    }

    static get displayName() {
      return displayName;
    }

    componentDidMount() {
      this.componentWillReceiveProps(this.props);
    }

    componentWillReceiveProps(props: InternalProps) {
      const node = ReactDom.findDOMNode(this) as HTMLElement;
      attachEventProps(node, props, this.props);
    }

    render() {
      const { children, forwardedRef, ...cProps } = this.props;

      const propsWithoutAttributeValues = Object.keys(cProps).reduce((oldValue, key) => {
        if (attributeValues.indexOf(key) === -1) {
          (oldValue as any)[key] = (cProps as any)[key];
        }
        return oldValue;
      }, {});

      return React.createElement(
        tagName,
        {
          ...propsWithoutAttributeValues,
          ref: forwardedRef,
        },
        children,
      );
    }
  }

  function forwardRef(props: InternalProps, ref: React.RefObject<ElementType>) {
    return <ReactComponent {...props} forwardedRef={ref} />;
  }
  forwardRef.displayName = displayName;

  return React.forwardRef<ElementType, PropType & IonicReactExternalProps>(forwardRef);
}

// packages/react-library-output/src/resources/createComponent.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import { attachEventProps, dashToPascalCase } from './utils';

export interface ReactExternalProps<ElementType> {
  ref?: React.RefObject<ElementType>;
  children?: React.ReactNode;
}
interface ReactInternalProps<ElementType> {
  forwardedRef?: React.RefObject<ElementType>;
  children?: React.ReactNode;
}
type InternalProps<AttributeProps, ElementType> = AttributeProps & ReactInternalProps<ElementType>;

export function createReactComponent<T extends object, E>(win: Window, tagName: string, component: any) {
  const displayName = dashToPascalCase(tagName);
  win.customElements.define(tagName, component);

  class ReactComponent extends React.Component<InternalProps<T, E>> {
    componentRef: React.RefObject<E>;

    constructor(props: T & ReactInternalProps<E>) {
      super(props);
      this.componentRef = React.createRef();
    }

    static get displayName() {
      return displayName;
    }

    componentDidMount() {
      this.componentWillReceiveProps(this.props);
    }

    componentWillReceiveProps(props: InternalProps<T, E>) {
      const node = ReactDOM.findDOMNode(this) as HTMLElement;
      attachEventProps(node, props);
    }

    render() {
      const { children, forwardedRef, ...cProps } = this.props;

      return React.createElement(
        tagName,
        {
          ...cProps,
          ref: forwardedRef
        },
        children
      );
    }
  }

  function forwardRef(props: InternalProps<T, E>, ref: React.Ref<E>) {
    return <ReactComponent {...props} forwardedRef={ref} />;
  }
  forwardRef.displayName = displayName;

  return React.forwardRef<E, T & ReactExternalProps<E>>(forwardRef);
}
