// packages/example-project/nuxt-app/components/Input.vue
<script>
import { ref } from 'vue';
import { MyInput } from 'component-library-vue';

console.log('22211', MyInput);


export default {
  name: 'Input',
  components: {
    MyInput,
  },
  setup() {
    const inputEvent = ref('');
    const changeEvent = ref('');

    const handleInput = (ev) => {
      console.log('handleInput', ev.target.value);
      inputEvent.value = ev.target.value;
    };

    const handleChange = (ev) => {
      console.log('handleChange', ev.target.value);
      changeEvent.value = ev.detail.value;
    };

    return {
      inputEvent,
      changeEvent,
      handleInput,
      handleChange,
    };
  },
};
</script>

<style scoped>
.inputResult {
  color: green;
}
</style>

<template>
  <div>
    <MyInput
      @onMyInput="handleInput"
      @onMyChange="handleChange"
    >
    </MyInput>
    <div class="inputResult">
      <p>Input Event: {{ inputEvent }}</p>
      <p>Change Event: {{ changeEvent }}</p>
    </div>
  </div>
</template>

// example-project/component-library-react/src/Input/Input.tsx
import { useState } from 'react';

import { MyInput } from '../components';

function Input() {
  const [inputEvent, setInputEvent] = useState<string>('');
  const [changeEvent, setChangeEvent] = useState<string>('');
  return (
    <>
      <MyInput
        onMyInput={(ev) => setInputEvent(`${ev.target.value}`)}
        onMyChange={(ev) => setChangeEvent(`${ev.detail.value}`)}
      />
      <div>
        <p>Input Event: {inputEvent}</p>
        <p>Change Event: {changeEvent}</p>
      </div>
    </>
  );
}

export default Input;
